### ISSUE TITLE
Stale ICA acknowledgements cause panic due to math.Int.Sub() resulting in negative balance

### ISSUE THREAD

**Issue by joe-bowman** [quicksilver-zone/quicksilver#1271]
## Summary of Bug

When an issue has caused a packet acknowledgement to become stale, and its receipt causes a balance to be updated, we run the risk of a panic when the balance becomes negative (due to an ICQ request updating to the new value before the ack is received).

## Expected Behaviour

The transaction should handle the case where a negative balance is received, and complete gracefully without triggering any further state changes.

## Version

v1.5.0

## Steps to Reproduce

Attempt to deliver Juno channel-163 (icacontroller-juno-1.delegate) <--> channel-495 (icahost) sequence 226.

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged/assigned

**Comment by joe-bowman** [comment]
Stack trace:
```
2024-03-13T08:18:57.102260Z ERROR ThreadId(34) relay_ack_packet_messages{src_chain=juno-1 src_port=icahost src_channel=channel-495 dst_chain=quicksilver-2}:relay{odata=packet-ack ->Destination @1-14604762; len=50}:send_messages_and_wait_commit{chain=quicksilver-2 tracking_id=packet-ack}:send_tx_with_account_sequence_retry{chain=quicksilver-2 account.sequence=28422}:estimate_gas: failed to simulate tx. propagating error to caller: gRPC call `send_tx_simulate` failed with status: status: Unknown, message: "recovered: negative coin amount\nstack:\ngoroutine 203059300 [running]:\nruntime/debug.Stack()\n\truntime/debug/stack.go:24 +0x5e\ngithub.com/cosmos/cosmos-sdk/baseapp.NewBaseApp.newDefaultRecoveryMiddleware.func1({0x216c040?, 0x31baba0})\n\tgithub.com/cosmos/cosmos-sdk@v0.46.16/baseapp/recovery.go:71 +0x26\ngithub.com/cosmos/cosmos-sdk/baseapp.NewBaseApp.newDefaultRecoveryMiddleware.newRecoveryMiddleware.func2({0x216c040?, 0x31baba0?})\n\tgithub.com/cosmos/cosmos-sdk@v0.46.16/baseapp/recovery.go:39 +0x2d\ngithub.com/cosmos/cosmos-sdk/baseapp.processRecovery({0x216c040, 0x31baba0}, 0xc0e4f0f380?)\n\tgithub.com/cosmos/cosmos-sdk@v0.46.16/baseapp/recovery.go:28 +0x2f\ngithub.com/cosmos/cosmos-sdk/baseapp.processRecovery({0x216c040, 0x31baba0}, 0xa?)\n\tgithub.com/cosmos/cosmos-sdk@v0.46.16/baseapp/recovery.go:33 +0x53\ngithub.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).runTx.func1()\n\tgithub.com/cosmos/cosmos-sdk@v0.46.16/baseapp/baseapp.go:642 +0xfe\npanic({0x216c040?, 0x31baba0?})\n\truntime/panic.go:914 +0x21f\ngithub.com/cosmos/cosmos-sdk/types.Coins.Sub(...)\n\tgithub.com/cosmos/cosmos-sdk@v0.46.16/types/coin.go:372\ngithub.com/quicksilver-zone/quicksilver/x/interchainstaking/keeper.(*Keeper).HandleDelegate(_, {{0x31e8f08, 0x4757260}, {0x31fc680, 0xc123dd2d40}, {{0xb, 0x0}, {0xc0fd0b83f1, 0xd}, 0x614636, ...}, ...}, ...)\n\tgithub.com/quicksilver-zone/quicksilver/x/interchainstaking/keeper/ibc_packet_handlers.go:1028 +0xbe8\ngithub.com/quicksilver-zone/quicksilver/x/interchainstaking/keeper.(*Keeper).HandleAcknowledgement(_, {{0x31e8f08, 0x4757260}, {0x31fc680, 0xc123dd2d40}, {{0xb, 0x0}, {0xc0fd0b83f1, 0xd}, 0x614636, ...}, ...}, ...)\n\tgithub.com/quicksilver-zone/quicksilver/x/interchainstaking/keeper/ibc_packet_handlers.go:196 +0x10b6\ngithub.com/quicksilver-zone/quicksilver/x/interchainstaking.IBCModule.OnAcknowledgementPacket({_}, {{0x31e8f08, 0x4757260}, {0x31fc680, 0xc123dd2d40}, {{0xb, 0x0}, {0xc0fd0b83f1, 0xd}, 0x614636, ...}, ...}, ...)\n\tgithub.com/quicksilver-zone/quicksilver/x/interchainstaking/ibc_module.go:127 +0x27e\ngithub.com/cosmos/ibc-go/v5/modules/apps/27-interchain-accounts/controller.IBCMiddleware.OnAcknowledgementPacket({{0x31f9b80, 0xc00178d500}, {{0x31cb668, 0xc0015d0930}, {0x31fc530, 0xc001393a50}, {{0x31fc530, 0xc001393a50}, 0xc0000c1ff0, {0x31cb668, ...}, ...}, ...}}, ...)\n\tgithub.com/cosmos/ibc-go/v5@v5.3.2/modules/apps/27-interchain-accounts/controller/ibc_middleware.go:159 +0x1e5\ngithub.com/cosmos/ibc-go/v5/modules/core/keeper.Keeper.Acknowledgement({{0x0, 0x0}, {0x31fc530, 0xc001393a50}, {{0x31cb668, 0xc0015d0910}, {0x31fc530, 0xc001393a50}, {{0x31fc530, 0xc001393a50}, ...}, ...}, ...}, ...)\n\tgithub.com/cosmos/ibc-go/v5@v5.3.2/modules/core/keeper/msg_server.go:615 +0x55f\ngithub.com/cosmos/ibc-go/v5/modules/core/04-channel/types._Msg_Acknowledgement_Handler.func1({0x31e9448, 0xc1578041b0}, {0x24d8840?, 0xc1498a6b60})\n\tgithub.com/cosmos/ibc-go/v5@v5.3.2/modules/core/04-channel/types/tx.pb.go:1376 +0x72\ngithub.com/cosmos/cosmos-sdk/baseapp.(*MsgServiceRouter).RegisterService.func2.1({0x31e8f78, 0xc02c34c2c0}, {0xc08fda8478?, 0x411a85?}, 0x2a0?, 0xc13b632468)\n\tgithub.com/cosmos/cosmos-sdk@v0.46.16/baseapp/msg_service_router.go:118 +0x93\ngithub.com/cosmos/ibc-go/v5/modules/core/04-channel/types._Msg_Acknowledgement_Handler({0x2588920?, 0xc000153b80}, {0x31e8f78, 0xc02c34c2c0}, 0x2ca3be0, 0xc02e3d6cc0)\n\tgithub.com/cosmos/ibc-go/v5@v5.3.2/modules/core/04-channel/types/tx.pb.go:1378 +0x135\ngithub.com/cosmos/cosmos-sdk/baseapp.(*MsgServiceRouter).RegisterService.func2({{0x31e8f08, 0x4757260}, {0x31fc680, 0xc123dd2d40}, {{0xb, 0x0}, {0xc0fd0b83f1, 0xd}, 0x614636, {0x17e83a5a, ...}, ...}, ...}, ...)\n\tgithub.com/cosmos/cosmos-sdk@v0.46.16/baseapp/msg_service_router.go:145 +0x3a3\ngithub.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).runMsgs(_, {{0x31e8f08, 0x4757260}, {0x31fc680, 0xc123dd2d40}, {{0xb, 0x0}, {0xc0fd0b83f1, 0xd}, 0x614636, ...}, ...}, ...)\n\tgithub.com/cosmos/cosmos-sdk@v0.46.16/baseapp/baseapp.go:788 +0x285\ngithub.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).runTx(0xc00179c540, 0x2, {0xc030b80000, 0x12600, 0x14000})\n\tgithub.com/cosmos/cosmos-sdk@v0.46.16/baseapp/baseapp.go:728 +0xd05\ngithub.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).Simulate(...)\n\tgithub.com/cosmos/cosmos-sdk@v0.46.16/baseapp/test_helpers.go:25\ngithub.com/cosmos/cosmos-sdk/x/auth/tx.txServer.Simulate({{{0x0, 0x0, 0x0}, {0x320e080, 0xc09cd0a1c0}, 0x0, {0xc0017434c0, 0xd}, {0x3202d10, 0xc000b216d0}, ...}, ...}, ...)\n\tgithub.com/cosmos/cosmos-sdk@v0.46.16/x/auth/tx/service.go:132 +0x129\ngithub.com/cosmos/cosmos-sdk/types/tx._Service_Simulate_Handler.func1({0x31e9448, 0xc12a27b6e0}, {0x24cc7c0?, 0xc0607f6960})\n\tgithub.com/cosmos/cosmos-sdk@v0.46.16/types/tx/service.pb.go:933 +0x72\ngithub.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).RegisterGRPCServer.func1({0x31e9448, 0xc13dc986c0}, {0x24cc7c0, 0xc0607f6960}, 0xc0607f6980?, 0xc12a5d2930)\n\tgithub.com/cosmos/cosmos-sdk@v0.46.16/baseapp/grpcserver.go:68 +0x391\ngithub.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).RegisterGRPCServer.func2.ChainUnaryServer.func2.1({0x31e9448?, 0xc13dc986c0?}, {0x24cc7c0?, 0xc0607f6960?})\n\tgithub.com/grpc-ecosystem/go-grpc-middleware@v1.4.0/chain.go:48 +0x45\ngithub.com/grpc-ecosystem/go-grpc-middleware/recovery.UnaryServerInterceptor.func1({0x31e9448?, 0xc13dc986c0?}, {0x24cc7c0?, 0xc0607f6960?}, 0xc12a5d2930?, 0x0?)\n\tgithub.com/grpc-ecosystem/go-grpc-middleware@v1.4.0/recovery/interceptors.go:33 +0xb0\ngithub.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).RegisterGRPCServer.func2.ChainUnaryServer.func2({0x31e9448, 0xc13dc986c0}, {0x24cc7c0, 0xc0607f6960}, 0xc0607f6980, 0x414325?)\n\tgithub.com/grpc-ecosystem/go-grpc-middleware@v1.4.0/chain.go:53 +0x135\ngithub.com/cosmos/cosmos-sdk/types/tx._Service_Simulate_Handler({0x245a220?, 0xc09d322000}, {0x31e9448, 0xc13dc986c0}, 0xc02a501080, 0xc13dc986f0)\n\tgithub.com/cosmos/cosmos-sdk@v0.46.16/types/tx/service.pb.go:935 +0x135\ngithub.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).RegisterGRPCServer.func2({0x245a220, 0xc09d322000}, {0x31e9448, 0xc13dc986c0}, 0x255f880?, 0xc02ab01320?)\n\tgithub.com/cosmos/cosmos-sdk@v0.46.16/baseapp/grpcserver.go:82 +0x112\ngoogle.golang.org/grpc.(*Server).processUnaryRPC(0xc0e7fa6600, {0x31e9448, 0xc13dc98600}, {0x31fa0c0, 0xc021281ba0}, 0xc02ab01320, 0xc01a8f4fc0, 0xc0c5cf1600, 0x0)\n\tgoogle.golang.org/grpc@v1.62.1/server.go:1386 +0xe23\ngoogle.golang.org/grpc.(*Server).handleStream(0xc0e7fa6600, {0x31fa0c0, 0xc021281ba0}, 0xc02ab01320)\n\tgoogle.golang.org/grpc@v1.62.1/server.go:1797 +0x100c\ngoogle.golang.org/grpc.(*Server).serveStreams.func2.1()\n\tgoogle.golang.org/grpc@v1.62.1/server.go:1027 +0x8b\ncreated by google.golang.org/grpc.(*Server).serveStreams.func2 in goroutine 203059299\n\tgoogle.golang.org/grpc@v1.62.1/server.go:1038 +0x135\n: panic [cosmos/cosmos-sdk@v0.46.16/baseapp/recovery.go:69] With gas wanted: '150000000' and gas used: '1560438' ", details: [], metadata: MetadataMap { headers: {"content-type": "application/grpc", "x-cosmos-block-height": "6374966"} }
2024-03-13T08:18:57.102455Z ERROR ThreadId(34) relay_ack_packet_messages{src_chain=juno-1 src_port=icahost src_channel=channel-495 dst_chain=quicksilver-2}:relay{odata=packet-ack ->Destination @1-14604762; len=50}:send_messages_and_wait_commit{chain=quicksilver-2 tracking_id=packet-ack}:send_tx_with_account_sequence_retry{chain=quicksilver-2 account.sequence=28422}: gas estimation failed or encountered another unrecoverable error error=gRPC call `send_tx_simulate` failed with status: status: Unknown, message: "recovered: negative coin amount\nstack:\ngoroutine 203059300 [running]:\nruntime/debug.Stack()\n\truntime/debug/stack.go:24 +0x5e\ngithub.com/cosmos/cosmos-sdk/baseapp.NewBaseApp.newDefaultRecoveryMiddleware.func1({0x216c040?, 0x31baba0})\n\tgithub.com/cosmos/cosmos-sdk@v0.46.16/baseapp/recovery.go:71 +0x26\ngithub.com/cosmos/cosmos-sdk/baseapp.NewBaseApp.newDefaultRecoveryMiddleware.newRecoveryMiddleware.func2({0x216c040?, 0x31baba0?})\n\tgithub.com/cosmos/cosmos-sdk@v0.46.16/baseapp/recovery.go:39 +0x2d\ngithub.com/cosmos/cosmos-sdk/baseapp.processRecovery({0x216c040, 0x31baba0}, 0xc0e4f0f380?)\n\tgithub.com/cosmos/cosmos-sdk@v0.46.16/baseapp/recovery.go:28 +0x2f\ngithub.com/cosmos/cosmos-sdk/baseapp.processRecovery({0x216c040, 0x31baba0}, 0xa?)\n\tgithub.com/cosmos/cosmos-sdk@v0.46.16/baseapp/recovery.go:33 +0x53\ngithub.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).runTx.func1()\n\tgithub.com/cosmos/cosmos-sdk@v0.46.16/baseapp/baseapp.go:642 +0xfe\npanic({0x216c040?, 0x31baba0?})\n\truntime/panic.go:914 +0x21f\ngithub.com/cosmos/cosmos-sdk/types.Coins.Sub(...)\n\tgithub.com/cosmos/cosmos-sdk@v0.46.16/types/coin.go:372\ngithub.com/quicksilver-zone/quicksilver/x/interchainstaking/keeper.(*Keeper).HandleDelegate(_, {{0x31e8f08, 0x4757260}, {0x31fc680, 0xc123dd2d40}, {{0xb, 0x0}, {0xc0fd0b83f1, 0xd}, 0x614636, ...}, ...}, ...)\n\tgithub.com/quicksilver-zone/quicksilver/x/interchainstaking/keeper/ibc_packet_handlers.go:1028 +0xbe8\ngithub.com/quicksilver-zone/quicksilver/x/interchainstaking/keeper.(*Keeper).HandleAcknowledgement(_, {{0x31e8f08, 0x4757260}, {0x31fc680, 0xc123dd2d40}, {{0xb, 0x0}, {0xc0fd0b83f1, 0xd}, 0x614636, ...}, ...}, ...)\n\tgithub.com/quicksilver-zone/quicksilver/x/interchainstaking/keeper/ibc_packet_handlers.go:196 +0x10b6\ngithub.com/quicksilver-zone/quicksilver/x/interchainstaking.IBCModule.OnAcknowledgementPacket({_}, {{0x31e8f08, 0x4757260}, {0x31fc680, 0xc123dd2d40}, {{0xb, 0x0}, {0xc0fd0b83f1, 0xd}, 0x614636, ...}, ...}, ...)\n\tgithub.com/quicksilver-zone/quicksilver/x/interchainstaking/ibc_module.go:127 +0x27e\ngithub.com/cosmos/ibc-go/v5/modules/apps/27-interchain-accounts/controller.IBCMiddleware.OnAcknowledgementPacket({{0x31f9b80, 0xc00178d500}, {{0x31cb668, 0xc0015d0930}, {0x31fc530, 0xc001393a50}, {{0x31fc530, 0xc001393a50}, 0xc0000c1ff0, {0x31cb668, ...}, ...}, ...}}, ...)\n\tgithub.com/cosmos/ibc-go/v5@v5.3.2/modules/apps/27-interchain-accounts/controller/ibc_middleware.go:159 +0x1e5\ngithub.com/cosmos/ibc-go/v5/modules/core/keeper.Keeper.Acknowledgement({{0x0, 0x0}, {0x31fc530, 0xc001393a50}, {{0x31cb668, 0xc0015d0910}, {0x31fc530, 0xc001393a50}, {{0x31fc530, 0xc001393a50}, ...}, ...}, ...}, ...)\n\tgithub.com/cosmos/ibc-go/v5@v5.3.2/modules/core/keeper/msg_server.go:615 +0x55f\ngithub.com/cosmos/ibc-go/v5/modules/core/04-channel/types._Msg_Acknowledgement_Handler.func1({0x31e9448, 0xc1578041b0}, {0x24d8840?, 0xc1498a6b60})\n\tgithub.com/cosmos/ibc-go/v5@v5.3.2/modules/core/04-channel/types/tx.pb.go:1376 +0x72\ngithub.com/cosmos/cosmos-sdk/baseapp.(*MsgServiceRouter).RegisterService.func2.1({0x31e8f78, 0xc02c34c2c0}, {0xc08fda8478?, 0x411a85?}, 0x2a0?, 0xc13b632468)\n\tgithub.com/cosmos/cosmos-sdk@v0.46.16/baseapp/msg_service_router.go:118 +0x93\ngithub.com/cosmos/ibc-go/v5/modules/core/04-channel/types._Msg_Acknowledgement_Handler({0x2588920?, 0xc000153b80}, {0x31e8f78, 0xc02c34c2c0}, 0x2ca3be0, 0xc02e3d6cc0)\n\tgithub.com/cosmos/ibc-go/v5@v5.3.2/modules/core/04-channel/types/tx.pb.go:1378 +0x135\ngithub.com/cosmos/cosmos-sdk/baseapp.(*MsgServiceRouter).RegisterService.func2({{0x31e8f08, 0x4757260}, {0x31fc680, 0xc123dd2d40}, {{0xb, 0x0}, {0xc0fd0b83f1, 0xd}, 0x614636, {0x17e83a5a, ...}, ...}, ...}, ...)\n\tgithub.com/cosmos/cosmos-sdk@v0.46.16/baseapp/msg_service_router.go:145 +0x3a3\ngithub.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).runMsgs(_, {{0x31e8f08, 0x4757260}, {0x31fc680, 0xc123dd2d40}, {{0xb, 0x0}, {0xc0fd0b83f1, 0xd}, 0x614636, ...}, ...}, ...)\n\tgithub.com/cosmos/cosmos-sdk@v0.46.16/baseapp/baseapp.go:788 +0x285\ngithub.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).runTx(0xc00179c540, 0x2, {0xc030b80000, 0x12600, 0x14000})\n\tgithub.com/cosmos/cosmos-sdk@v0.46.16/baseapp/baseapp.go:728 +0xd05\ngithub.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).Simulate(...)\n\tgithub.com/cosmos/cosmos-sdk@v0.46.16/baseapp/test_helpers.go:25\ngithub.com/cosmos/cosmos-sdk/x/auth/tx.txServer.Simulate({{{0x0, 0x0, 0x0}, {0x320e080, 0xc09cd0a1c0}, 0x0, {0xc0017434c0, 0xd}, {0x3202d10, 0xc000b216d0}, ...}, ...}, ...)\n\tgithub.com/cosmos/cosmos-sdk@v0.46.16/x/auth/tx/service.go:132 +0x129\ngithub.com/cosmos/cosmos-sdk/types/tx._Service_Simulate_Handler.func1({0x31e9448, 0xc12a27b6e0}, {0x24cc7c0?, 0xc0607f6960})\n\tgithub.com/cosmos/cosmos-sdk@v0.46.16/types/tx/service.pb.go:933 +0x72\ngithub.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).RegisterGRPCServer.func1({0x31e9448, 0xc13dc986c0}, {0x24cc7c0, 0xc0607f6960}, 0xc0607f6980?, 0xc12a5d2930)\n\tgithub.com/cosmos/cosmos-sdk@v0.46.16/baseapp/grpcserver.go:68 +0x391\ngithub.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).RegisterGRPCServer.func2.ChainUnaryServer.func2.1({0x31e9448?, 0xc13dc986c0?}, {0x24cc7c0?, 0xc0607f6960?})\n\tgithub.com/grpc-ecosystem/go-grpc-middleware@v1.4.0/chain.go:48 +0x45\ngithub.com/grpc-ecosystem/go-grpc-middleware/recovery.UnaryServerInterceptor.func1({0x31e9448?, 0xc13dc986c0?}, {0x24cc7c0?, 0xc0607f6960?}, 0xc12a5d2930?, 0x0?)\n\tgithub.com/grpc-ecosystem/go-grpc-middleware@v1.4.0/recovery/interceptors.go:33 +0xb0\ngithub.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).RegisterGRPCServer.func2.ChainUnaryServer.func2({0x31e9448, 0xc13dc986c0}, {0x24cc7c0, 0xc0607f6960}, 0xc0607f6980, 0x414325?)\n\tgithub.com/grpc-ecosystem/go-grpc-middleware@v1.4.0/chain.go:53 +0x135\ngithub.com/cosmos/cosmos-sdk/types/tx._Service_Simulate_Handler({0x245a220?, 0xc09d322000}, {0x31e9448, 0xc13dc986c0}, 0xc02a501080, 0xc13dc986f0)\n\tgithub.com/cosmos/cosmos-sdk@v0.46.16/types/tx/service.pb.go:935 +0x135\ngithub.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).RegisterGRPCServer.func2({0x245a220, 0xc09d322000}, {0x31e9448, 0xc13dc986c0}, 0x255f880?, 0xc02ab01320?)\n\tgithub.com/cosmos/cosmos-sdk@v0.46.16/baseapp/grpcserver.go:82 +0x112\ngoogle.golang.org/grpc.(*Server).processUnaryRPC(0xc0e7fa6600, {0x31e9448, 0xc13dc98600}, {0x31fa0c0, 0xc021281ba0}, 0xc02ab01320, 0xc01a8f4fc0, 0xc0c5cf1600, 0x0)\n\tgoogle.golang.org/grpc@v1.62.1/server.go:1386 +0xe23\ngoogle.golang.org/grpc.(*Server).handleStream(0xc0e7fa6600, {0x31fa0c0, 0xc021281ba0}, 0xc02ab01320)\n\tgoogle.golang.org/grpc@v1.62.1/server.go:1797 +0x100c\ngoogle.golang.org/grpc.(*Server).serveStreams.func2.1()\n\tgoogle.golang.org/grpc@v1.62.1/server.go:1027 +0x8b\ncreated by google.golang.org/grpc.(*Server).serveStreams.func2 in goroutine 203059299\n\tgoogle.golang.org/grpc@v1.62.1/server.go:1038 +0x135\n: panic [cosmos/cosmos-sdk@v0.46.16/baseapp/recovery.go:69] With gas wanted: '150000000' and gas used: '1560438' ", details: [], metadata: MetadataMap { headers: {"content-type": "application/grpc", "x-cosmos-block-height": "6374966"} }
2024-03-13T08:18:57.102637Z ERROR ThreadId(01) Failed to relay reverse ack packets: link failed with underlying error: gRPC call `send_tx_simulate` failed with status: status: Unknown, message: "recovered: negative coin amount\nstack:\ngoroutine 203059300 [running]:\nruntime/debug.Stack()\n\truntime/debug/stack.go:24 +0x5e\ngithub.com/cosmos/cosmos-sdk/baseapp.NewBaseApp.newDefaultRecoveryMiddleware.func1({0x216c040?, 0x31baba0})\n\tgithub.com/cosmos/cosmos-sdk@v0.46.16/baseapp/recovery.go:71 +0x26\ngithub.com/cosmos/cosmos-sdk/baseapp.NewBaseApp.newDefaultRecoveryMiddleware.newRecoveryMiddleware.func2({0x216c040?, 0x31baba0?})\n\tgithub.com/cosmos/cosmos-sdk@v0.46.16/baseapp/recovery.go:39 +0x2d\ngithub.com/cosmos/cosmos-sdk/baseapp.processRecovery({0x216c040, 0x31baba0}, 0xc0e4f0f380?)\n\tgithub.com/cosmos/cosmos-sdk@v0.46.16/baseapp/recovery.go:28 +0x2f\ngithub.com/cosmos/cosmos-sdk/baseapp.processRecovery({0x216c040, 0x31baba0}, 0xa?)\n\tgithub.com/cosmos/cosmos-sdk@v0.46.16/baseapp/recovery.go:33 +0x53\ngithub.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).runTx.func1()\n\tgithub.com/cosmos/cosmos-sdk@v0.46.16/baseapp/baseapp.go:642 +0xfe\npanic({0x216c040?, 0x31baba0?})\n\truntime/panic.go:914 +0x21f\ngithub.com/cosmos/cosmos-sdk/types.Coins.Sub(...)\n\tgithub.com/cosmos/cosmos-sdk@v0.46.16/types/coin.go:372\ngithub.com/quicksilver-zone/quicksilver/x/interchainstaking/keeper.(*Keeper).HandleDelegate(_, {{0x31e8f08, 0x4757260}, {0x31fc680, 0xc123dd2d40}, {{0xb, 0x0}, {0xc0fd0b83f1, 0xd}, 0x614636, ...}, ...}, ...)\n\tgithub.com/quicksilver-zone/quicksilver/x/interchainstaking/keeper/ibc_packet_handlers.go:1028 +0xbe8\ngithub.com/quicksilver-zone/quicksilver/x/interchainstaking/keeper.(*Keeper).HandleAcknowledgement(_, {{0x31e8f08, 0x4757260}, {0x31fc680, 0xc123dd2d40}, {{0xb, 0x0}, {0xc0fd0b83f1, 0xd}, 0x614636, ...}, ...}, ...)\n\tgithub.com/quicksilver-zone/quicksilver/x/interchainstaking/keeper/ibc_packet_handlers.go:196 +0x10b6\ngithub.com/quicksilver-zone/quicksilver/x/interchainstaking.IBCModule.OnAcknowledgementPacket({_}, {{0x31e8f08, 0x4757260}, {0x31fc680, 0xc123dd2d40}, {{0xb, 0x0}, {0xc0fd0b83f1, 0xd}, 0x614636, ...}, ...}, ...)\n\tgithub.com/quicksilver-zone/quicksilver/x/interchainstaking/ibc_module.go:127 +0x27e\ngithub.com/cosmos/ibc-go/v5/modules/apps/27-interchain-accounts/controller.IBCMiddleware.OnAcknowledgementPacket({{0x31f9b80, 0xc00178d500}, {{0x31cb668, 0xc0015d0930}, {0x31fc530, 0xc001393a50}, {{0x31fc530, 0xc001393a50}, 0xc0000c1ff0, {0x31cb668, ...}, ...}, ...}}, ...)\n\tgithub.com/cosmos/ibc-go/v5@v5.3.2/modules/apps/27-interchain-accounts/controller/ibc_middleware.go:159 +0x1e5\ngithub.com/cosmos/ibc-go/v5/modules/core/keeper.Keeper.Acknowledgement({{0x0, 0x0}, {0x31fc530, 0xc001393a50}, {{0x31cb668, 0xc0015d0910}, {0x31fc530, 0xc001393a50}, {{0x31fc530, 0xc001393a50}, ...}, ...}, ...}, ...)\n\tgithub.com/cosmos/ibc-go/v5@v5.3.2/modules/core/keeper/msg_server.go:615 +0x55f\ngithub.com/cosmos/ibc-go/v5/modules/core/04-channel/types._Msg_Acknowledgement_Handler.func1({0x31e9448, 0xc1578041b0}, {0x24d8840?, 0xc1498a6b60})\n\tgithub.com/cosmos/ibc-go/v5@v5.3.2/modules/core/04-channel/types/tx.pb.go:1376 +0x72\ngithub.com/cosmos/cosmos-sdk/baseapp.(*MsgServiceRouter).RegisterService.func2.1({0x31e8f78, 0xc02c34c2c0}, {0xc08fda8478?, 0x411a85?}, 0x2a0?, 0xc13b632468)\n\tgithub.com/cosmos/cosmos-sdk@v0.46.16/baseapp/msg_service_router.go:118 +0x93\ngithub.com/cosmos/ibc-go/v5/modules/core/04-channel/types._Msg_Acknowledgement_Handler({0x2588920?, 0xc000153b80}, {0x31e8f78, 0xc02c34c2c0}, 0x2ca3be0, 0xc02e3d6cc0)\n\tgithub.com/cosmos/ibc-go/v5@v5.3.2/modules/core/04-channel/types/tx.pb.go:1378 +0x135\ngithub.com/cosmos/cosmos-sdk/baseapp.(*MsgServiceRouter).RegisterService.func2({{0x31e8f08, 0x4757260}, {0x31fc680, 0xc123dd2d40}, {{0xb, 0x0}, {0xc0fd0b83f1, 0xd}, 0x614636, {0x17e83a5a, ...}, ...}, ...}, ...)\n\tgithub.com/cosmos/cosmos-sdk@v0.46.16/baseapp/msg_service_router.go:145 +0x3a3\ngithub.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).runMsgs(_, {{0x31e8f08, 0x4757260}, {0x31fc680, 0xc123dd2d40}, {{0xb, 0x0}, {0xc0fd0b83f1, 0xd}, 0x614636, ...}, ...}, ...)\n\tgithub.com/cosmos/cosmos-sdk@v0.46.16/baseapp/baseapp.go:788 +0x285\ngithub.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).runTx(0xc00179c540, 0x2, {0xc030b80000, 0x12600, 0x14000})\n\tgithub.com/cosmos/cosmos-sdk@v0.46.16/baseapp/baseapp.go:728 +0xd05\ngithub.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).Simulate(...)\n\tgithub.com/cosmos/cosmos-sdk@v0.46.16/baseapp/test_helpers.go:25\ngithub.com/cosmos/cosmos-sdk/x/auth/tx.txServer.Simulate({{{0x0, 0x0, 0x0}, {0x320e080, 0xc09cd0a1c0}, 0x0, {0xc0017434c0, 0xd}, {0x3202d10, 0xc000b216d0}, ...}, ...}, ...)\n\tgithub.com/cosmos/cosmos-sdk@v0.46.16/x/auth/tx/service.go:132 +0x129\ngithub.com/cosmos/cosmos-sdk/types/tx._Service_Simulate_Handler.func1({0x31e9448, 0xc12a27b6e0}, {0x24cc7c0?, 0xc0607f6960})\n\tgithub.com/cosmos/cosmos-sdk@v0.46.16/types/tx/service.pb.go:933 +0x72\ngithub.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).RegisterGRPCServer.func1({0x31e9448, 0xc13dc986c0}, {0x24cc7c0, 0xc0607f6960}, 0xc0607f6980?, 0xc12a5d2930)\n\tgithub.com/cosmos/cosmos-sdk@v0.46.16/baseapp/grpcserver.go:68 +0x391\ngithub.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).RegisterGRPCServer.func2.ChainUnaryServer.func2.1({0x31e9448?, 0xc13dc986c0?}, {0x24cc7c0?, 0xc0607f6960?})\n\tgithub.com/grpc-ecosystem/go-grpc-middleware@v1.4.0/chain.go:48 +0x45\ngithub.com/grpc-ecosystem/go-grpc-middleware/recovery.UnaryServerInterceptor.func1({0x31e9448?, 0xc13dc986c0?}, {0x24cc7c0?, 0xc0607f6960?}, 0xc12a5d2930?, 0x0?)\n\tgithub.com/grpc-ecosystem/go-grpc-middleware@v1.4.0/recovery/interceptors.go:33 +0xb0\ngithub.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).RegisterGRPCServer.func2.ChainUnaryServer.func2({0x31e9448, 0xc13dc986c0}, {0x24cc7c0, 0xc0607f6960}, 0xc0607f6980, 0x414325?)\n\tgithub.com/grpc-ecosystem/go-grpc-middleware@v1.4.0/chain.go:53 +0x135\ngithub.com/cosmos/cosmos-sdk/types/tx._Service_Simulate_Handler({0x245a220?, 0xc09d322000}, {0x31e9448, 0xc13dc986c0}, 0xc02a501080, 0xc13dc986f0)\n\tgithub.com/cosmos/cosmos-sdk@v0.46.16/types/tx/service.pb.go:935 +0x135\ngithub.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).RegisterGRPCServer.func2({0x245a220, 0xc09d322000}, {0x31e9448, 0xc13dc986c0}, 0x255f880?, 0xc02ab01320?)\n\tgithub.com/cosmos/cosmos-sdk@v0.46.16/baseapp/grpcserver.go:82 +0x112\ngoogle.golang.org/grpc.(*Server).processUnaryRPC(0xc0e7fa6600, {0x31e9448, 0xc13dc98600}, {0x31fa0c0, 0xc021281ba0}, 0xc02ab01320, 0xc01a8f4fc0, 0xc0c5cf1600, 0x0)\n\tgoogle.golang.org/grpc@v1.62.1/server.go:1386 +0xe23\ngoogle.golang.org/grpc.(*Server).handleStream(0xc0e7fa6600, {0x31fa0c0, 0xc021281ba0}, 0xc02ab01320)\n\tgoogle.golang.org/grpc@v1.62.1/server.go:1797 +0x100c\ngoogle.golang.org/grpc.(*Server).serveStreams.func2.1()\n\tgoogle.golang.org/grpc@v1.62.1/server.go:1027 +0x8b\ncreated by google.golang.org/grpc.(*Server).serveStreams.func2 in goroutine 203059299\n\tgoogle.golang.org/grpc@v1.62.1/server.go:1038 +0x135\n: panic [cosmos/cosmos-sdk@v0.46.16/baseapp/recovery.go:69] With gas wanted: '150000000' and gas used: '1560438' ", details: [], metadata: MetadataMap { headers: {"content-type": "application/grpc", "x-cosmos-block-height": "6374966"} }
```
