### ISSUE TITLE
Panic in icq-relayer v1.0.0-alpha.0 on batch submission

### ISSUE THREAD

**Issue by joe-bowman** [quicksilver-zone/quicksilver#1643]
```
icq_1          | panic: runtime error: index out of range [0] with length 0
icq_1          | 
icq_1          | goroutine 624 [running]:
icq_1          | github.com/quicksilver-zone/quicksilver/icq-relayer/pkg/runner.getHeader({0x2b09d48, 0x3d589c0}, 0xc0006e5680, 0xc00017af50, {0xc0013a51f0, 0xf}, 0x668223, {0x2ae7700, 0xc001349180}, 0x0, ...)
icq_1          | 	/src/app/pkg/runner/run.go:553 +0x6ab
icq_1          | github.com/quicksilver-zone/quicksilver/icq-relayer/pkg/runner.asyncCacheClientUpdate({0x2b09d48, 0x3d589c0}, 0xc0006e5680, 0xc00017af50, {{0x0, 0x0}, {0xc005ac5100, 0xc}, {0x0, 0x0}, ...}, ...)
icq_1          | 	/src/app/pkg/runner/run.go:504 +0x56c
icq_1          | github.com/quicksilver-zone/quicksilver/icq-relayer/pkg/runner.FlushSendQueue.func1()
icq_1          | 	/src/app/pkg/runner/run.go:614 +0x176
icq_1          | created by github.com/quicksilver-zone/quicksilver/icq-relayer/pkg/runner.FlushSendQueue in goroutine 155
icq_1          | 	/src/app/pkg/runner/run.go:613 +0x5d8
```

**Comment by odeke-em** [comment]
Hey @joe-bowman @faddat, was that code in a private and unreleased fork? None of the commits in the repository match "asyncCacheClientUpdate" which appears in your reported stack trace as per this shell code

```shell
cd pkg/runner && git log . | grep "commit" | cut -d" " -f2 | \
   while read commit; do git checkout $commit 2>/dev/null \
   1>/dev/null && git grep -in "asyncCacheClientUpdate"; done \
   && git checkout main 2>/dev/null 1>/dev/null && cd $OLDPWD
```

which goes through all the commits ever made inside pkg/runner and searches for hits for "asyncCacheClientUpdate" but it produces no output.

Please elaborate more or we should perhaps close this issue.
